/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_activemq_artemis_bug_BugContext */

#ifndef _Included_org_apache_activemq_artemis_bug_BugContext
#define _Included_org_apache_activemq_artemis_bug_BugContext
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_activemq_artemis_bug_BugContext_EXPECTED_NATIVE_VERSION
#define org_apache_activemq_artemis_bug_BugContext_EXPECTED_NATIVE_VERSION 2L
/*
 * Class:     org_apache_activemq_artemis_bug_BugContext
 * Method:    hello
 * Signature: (Lorg/apache/activemq/artemis/bug/SubmitInformation;)V
 */
JNIEXPORT void JNICALL Java_org_apache_activemq_artemis_bug_BugContext_hello
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
